spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-microservice


#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/customer
#server:
#  port: 8091